before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"


language: node_js


node_js:
  - 8
  - 10


notifications:
  email: false
