allowUnused: []

devFilePatterns:
  - '{features,spec,test}/**/*'
  - '**/*{.,_,-}{spec,test}.js'

devScripts:
  - lint
  - publish
  - test
  - version

filePattern: '**/*.js'

ignoreFilePatterns:
  - 'node_modules/**/*'

stripLoaders: false

transpilers: []
