# array of strings or regular expressions to match against a module name
# to determine if it is allowed to be unused
#
# Please create an issue at
# https://github.com/charlierudolph/dependency-lint/issues
# anytime you need to use this
allowUnused: []

# array of path patterns to match againt a filename
# to determine if it is used only for development
#   (see https://github.com/isaacs/minimatch)
devFilePatterns:
  - '{features,spec,test}/**/*'
  - '**/*_{spec,test}.js'

# array of strings or regular expressions to match against a script name
# in your `package.json` to determine if it is used only for development
devScripts:
  - lint
  - publish
  - test

# path pattern to match against a filename to determine if it should be parsed.
#   (see https://github.com/isaacs/minimatch)
#
# This is the starting point, devFilePatterns and ignoreFilePatterns should be
# subsets of this pattern
filePattern: '**/*.js'

# array of path patterns to match against a filename
# to determine if it should be ignored
#   (see https://github.com/isaacs/minimatch)
ignoreFilePatterns:
  - 'node_modules/**/*'

# boolean whether to ignore anything before a `!` in require statements
#
# Useful for:
#   webpack loaders - https://webpack.github.io/docs/loaders.html
#   RequireJS loader plugins - http://requirejs.org/docs/plugins.html
stripLoaders: false

# array of transpilers with properties 'extension' and 'module'.
#
# The module will be required and then the 'compile' property will be called
# with the file contents and the file path for each file with that extension
#
#   require(<module>).compile(fileContents, {filename: filePath});
#
transpilers: []
