executedModules:
  npmScripts:
    dev:
      - lint
      - publish
      - test
      - version

ignoreErrors:
  missing: []
  shouldBeDependency: []
  shouldBeDevDependency: []
  unused: []

requiredModules:
  files:
    dev:
      - '{features,spec,test}/**/*'
      - '**/*{.,_,-}{spec,test}.js'
    ignore:
      - 'node_modules/**/*'
    root: '**/*.js'
  stripLoaders: false
  transpilers: []
